[[kv_namespaces]]
binding = "SESSION_KV"
id = "c15c8297986a4bb7ad74f68a832c4074"
preview_id = "2af224c7dacb4497bb4b01bd284614f5"

[[d1_databases]]
binding = "DB"
database_name = "dot-strive"
database_id = "b2428095-b300-45be-9fbe-6024a0e1f1af"
migrations_dir = "./database/migrations"
